services:
  postgres:
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: rendres
      POSTGRES_PASSWORD: s3cr3t
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rendres", "-d", "auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net

  supertokens:
    image: supertokens/supertokens-postgresql:9.2.2
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://rendres:s3cr3t@postgres:5432/auth"
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

networks:
  net:

volumes:
  postgres:
