// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Guest struct {
	ID             int64     `db:"id" json:"id"`
	UserID         string    `db:"user_id" json:"user_id"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	Name           string    `db:"name" json:"name"`
	Phone          string    `db:"phone" json:"phone"`
	IsVegetarian   bool      `db:"is_vegetarian" json:"is_vegetarian"`
	Allergies      []string  `db:"allergies" json:"allergies"`
	NeedsTransport bool      `db:"needs_transport" json:"needs_transport"`
}

type Song struct {
	ID           int64     `db:"id" json:"id"`
	UserID       string    `db:"user_id" json:"user_id"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
	Name         string    `db:"name" json:"name"`
	Album        string    `db:"album" json:"album"`
	AlbumPicture string    `db:"album_picture" json:"album_picture"`
}
