// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	DeleteGuest(ctx context.Context, id int64) error
	DeleteUserGuest(ctx context.Context, userID string) error
	GetAllGuests(ctx context.Context, arg GetAllGuestsParams) ([]Guest, error)
	GetGuest(ctx context.Context, id int64) (Guest, error)
	GetUserGuests(ctx context.Context, userID string) ([]Guest, error)
	UpdateGuest(ctx context.Context, arg UpdateGuestParams) (Guest, error)
}

var _ Querier = (*Queries)(nil)
